/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.billing.gui.dialog.au;


import com.aldrin.billing.dao.impl.ProductDAOImpl;
import com.aldrin.billing.gui.JFrameApp;
import com.aldrin.billing.model.Product;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.JCommon;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogProductAU extends javax.swing.JDialog {

    private ProductDAOImpl productDAOImpl = new ProductDAOImpl();
    private JFrameApp jFrameCafSys;

    /**
     * Creates new form JDialogStudent
     */
    private Product product = new Product();
    static String title = "";

    public JDialogProductAU(JFrameApp jFrameSariPOS, boolean modal) {
        super(jFrameSariPOS, modal);
        initComponents();
        this.jFrameCafSys =jFrameSariPOS;
        setTitle("Add product");
        this.title = "New";
        jTextFieldProduct.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "PRODUCT");
        jTextFieldPrice.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "PRICE");
        jTextAreaDesription.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "DESCRIPTION");
        jButton1.setIcon(new FlatSVGIcon("svg/save.svg",24,24));
        
                

        

    }

    public JDialogProductAU(JFrameApp jFrameCafSys, boolean modal, Product product, String title) {
        super(jFrameCafSys, modal);
        initComponents();
        setTitle("Update product");
        this.product = product;
        this.title = title;
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        jTextFieldProduct.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "PRODUCT");
        jTextFieldPrice.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "RPICE");
        jTextAreaDesription.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "DESCRIPTION");
        jTextFieldProduct.setText(product.getProduct());
        jTextFieldPrice.setText(String.valueOf(product.getPrice()));
        jTextAreaDesription.setText(product.getDescription());

        jButton1.setIcon(new FlatSVGIcon("svg/edit.svg",24,24));
//        setUndecorated(true);

    }

    public JDialogProductAU(JFrameApp jFrameCafSys, boolean modal, String title, Product product) {
        super(jFrameCafSys, modal);
        initComponents();
        setTitle("Delete product");
        this.product = product;
        this.title = title;
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        jTextFieldProduct.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "PRODUCT");
        jTextFieldPrice.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "RPICE");
        jTextAreaDesription.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "DESCRIPTION");
        jTextFieldProduct.setText(product.getProduct());
        jTextFieldPrice.setText(product.getProduct());
        jTextAreaDesription.setText(product.getDescription());  
        jButton1.setIcon(new FlatSVGIcon("svg/delete.svg",24,24));
//        setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProduct = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDesription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student");

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("PRODUCT");
        jLabel1.setPreferredSize(new java.awt.Dimension(65, 25));
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 20));

        jTextFieldProduct.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel4.add(jTextFieldProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, 220, 25));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("PRICE");
        jLabel9.setPreferredSize(new java.awt.Dimension(55, 25));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 220, 20));

        jTextFieldPrice.setPreferredSize(new java.awt.Dimension(64, 25));
        jPanel4.add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 220, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("DESCRIPTION");
        jLabel10.setPreferredSize(new java.awt.Dimension(28, 25));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 20));

        jButton1.setText("Save");
        jButton1.setMargin(new java.awt.Insets(2, 0, 3, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 100, 32));

        jTextAreaDesription.setColumns(20);
        jTextAreaDesription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDesription);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 380, 170));

        jPanel5.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(424, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.title.equals("New")) {
            int response = JOptionPane.showConfirmDialog(jFrameCafSys, "Are you sure to save " + jTextFieldProduct.getText() + " " + jTextFieldPrice.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.product.setProduct(jTextFieldProduct.getText());
                this.product.setPrice(Float.parseFloat(jTextFieldPrice.getText()));
                this.product.setDescription(jTextAreaDesription.getText());
                productDAOImpl.addProduct(product);
                this.dispose();
            }
        } else if (this.title.equals("Update")) {
            int response = JOptionPane.showConfirmDialog(jFrameCafSys, "Are you sure to update " + jTextFieldProduct.getText() + " " + jTextFieldPrice.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.product.setProduct(jTextFieldProduct.getText());
                this.product.setPrice(Float.parseFloat(jTextFieldPrice.getText()));
                this.product.setDescription(jTextAreaDesription.getText());
                productDAOImpl.updateProduct(product);
                this.dispose();
            }
        } else if (this.title.equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(jFrameCafSys, "Are you sure to delete " + jTextFieldProduct.getText() + " " + jTextFieldPrice.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
//                productDAOImpl.deleteCustomer(product);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDesription;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldProduct;
    // End of variables declaration//GEN-END:variables

  

 
    
    

}
