/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.billing.gui.dialog;

import com.aldrin.billing.dao.impl.DBConnection;
import com.aldrin.billing.gui.JFrameApp;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JDialogDBSetup extends javax.swing.JDialog {

    /**
     * Creates new form JDialogDBSetup
     */
    private JFrameApp jFrameApp;

    public JDialogDBSetup(JFrameApp jFrameApp, boolean modal) {
        super(jFrameApp, modal);
        initComponents();
        jButtonTest.setIcon(new FlatSVGIcon("svg/test.svg", 20, 20));
        jButtonSave.setIcon(new FlatSVGIcon("svg/save.svg", 20, 20));
        //placeHolder
        jTextFieldIPAddress.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "IP Address");
        jTextFieldPort.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Port");
        jTextFieldDatabase.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Database name");
        jTextFieldUsername.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Username");
        jPasswordFieldPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Password");
        //reveal button
        jPasswordFieldPassword.putClientProperty(FlatClientProperties.STYLE, "showRevealButton:true;" + "showCapsLock:true");
        try {
            File fontStyle = new File("src/main/resources/fonts/TitanOne-Regular.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, fontStyle);
            jLabelTitle.setFont(font.deriveFont(18f));
//            jButtonLogin.setFont(font.deriveFont(16f));
        } catch (Exception e) {
            e.printStackTrace();
        }
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println("Dialog window is closing.");
                // Perform any action you want before the dialog closes
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIPAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDatabase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonTest = new javax.swing.JButton();
        jTextFieldPort = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 102, 153));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Database connection configuration");
        jLabelTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 490, 40));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 250, 490, -1));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("IP ADDRESS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 50, 490, -1));

        jTextFieldIPAddress.setPreferredSize(new java.awt.Dimension(64, 28));
        getContentPane().add(jTextFieldIPAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 65, 490, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("PORT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 490, -1));

        jTextFieldDatabase.setPreferredSize(new java.awt.Dimension(64, 28));
        getContentPane().add(jTextFieldDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 165, 490, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("DATABASE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 150, 490, -1));

        jTextFieldUsername.setPreferredSize(new java.awt.Dimension(64, 28));
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 215, 490, -1));

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 320, 230, 30));

        jButtonTest.setText("Test");
        jButtonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 320, 250, 30));

        jTextFieldPort.setPreferredSize(new java.awt.Dimension(64, 28));
        getContentPane().add(jTextFieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 115, 490, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("USERNAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 200, 490, -1));
        getContentPane().add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 265, 490, 30));

        setSize(new java.awt.Dimension(518, 415));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        String host = jTextFieldIPAddress.getText();
        String port = jTextFieldPort.getText();
        String dbName = jTextFieldDatabase.getText();
        String user = jTextFieldUsername.getText();
        String password = new String(jPasswordFieldPassword.getPassword());

        // Save the configuration
        DBConnection.saveProperties(host, port, dbName, user, password);

        // Close the dialog
        dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestActionPerformed
        String host = jTextFieldIPAddress.getText();
        String port = jTextFieldPort.getText();
        String dbName = jTextFieldDatabase.getText();
        String user = jTextFieldUsername.getText();
        String password = new String(jPasswordFieldPassword.getPassword());

        // Test connection
        if (DBConnection.testConnection(host, port, dbName, user, password)) {
            JOptionPane.showMessageDialog(jFrameApp, "Connection Successful!");
        } else {
            JOptionPane.showMessageDialog(jFrameApp, "Connection Failed. Please check your settings.");
        }
    }//GEN-LAST:event_jButtonTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonTest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldDatabase;
    private javax.swing.JTextField jTextFieldIPAddress;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
