/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aldrin.billing.gui;

import com.aldrin.billing.Billing;
import com.aldrin.billing.dao.impl.UserDAOImpl;
import com.aldrin.billing.gui.panel.JPanelReport;
import com.aldrin.billing.gui.panel.JPanelProduct;
import com.aldrin.billing.gui.panel.JPanelBilling;
import com.aldrin.billing.gui.panel.JPanelCustomer;
import com.aldrin.billing.gui.panel.JPanelDashboard;
import com.aldrin.billing.gui.panel.JPanelUser;
import com.aldrin.billing.model.User;
import com.aldrin.billing.swingx.ProfileIcon;
import com.aldrin.billing.util.LoginUser;
import com.aldrin.billing.util.LookAndFeelManager;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.util.prefs.Preferences;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JPopupMenu.Separator;
import javax.swing.SwingUtilities;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JFrameApp extends javax.swing.JFrame {

//    Font fontSize16 = UIManager.getFont("h3.regular.font");
    LoginUser loginUser = new LoginUser();
    private static final String USERNAME_PREF_KEY = "username";
    private static final String PASSWORD_PREF_KEY = "password";
    Preferences preferences = Preferences.userNodeForPackage(Billing.class);

    private CardLayout cardLayout = new CardLayout();
    private JPanel cardsPanel = new JPanel(cardLayout);
    JPanelCustomer panelCustomer = new JPanelCustomer(this);
    JPanelUser panelUser = new JPanelUser(this);

    /**
     * Creates new form JFrameApp
     */
    public JFrameApp() {
        initComponents();
        
        FlatLaf.updateUI();
        jMenuBar1.setVisible(false);
        FlatSVGIcon icon = new FlatSVGIcon("svg/billing_icon.svg", 24, 24);
        setIconImage(icon.getImage());
        setVisible(true);
        String storedUsername = preferences.get(USERNAME_PREF_KEY, null);
        String storedPassword = preferences.get(PASSWORD_PREF_KEY, null);
        jMenuItemLogout.setVisible(false);
        loginUser.setUser(null);

        saveLoginCredentials();

        cardsPanel.add(new JPanelDashboard(this), "Dashboard");
        cardsPanel.add(new JPanelBilling(this), "Billing");
        cardsPanel.add(new JPanelProduct(this), "Product");
        cardsPanel.add(new JPanelReport(this), "Report");
        cardsPanel.add(new JPanelUser(this), "User");
        cardsPanel.add(new JPanelCustomer(this), "Customer");
        jPanelContainer.add(cardsPanel, BorderLayout.CENTER);
        buttonSelected(jButtonDashboard);

        jButtonDashboard.putClientProperty("JButton.buttonType", "square");
        jButtonBilling.putClientProperty("JButton.buttonType", "square");
        jButtonProduct.putClientProperty("JButton.buttonType", "square");
        jButtonCustomer.putClientProperty("JButton.buttonType", "square");
        jButtonReports.putClientProperty("JButton.buttonType", "square");
        jButtonUser.putClientProperty("JButton.buttonType", "square");
        jButtonUserAccount.putClientProperty("JButton.buttonType", "square");
        popUpUser(this);
        Color ovalDarkColor = new java.awt.Color(128, 128, 128);
        Color ovalLightColor = new java.awt.Color(204, 204, 204);
        Color circleDarkColor = new java.awt.Color(51, 51, 51);
        Color circleLightColor = new java.awt.Color(255, 255, 255);
        if (new LoginUser().getUser() != null) {
            switchButtonThemeMode.setVisible(true);
            if (LookAndFeelManager.loadLookAndFeel().equals("FlatDarkLaf")) {
                switchButtonThemeMode.setDarkMode(false);
                switchButtonThemeMode.toggle();
                SwingUtilities.updateComponentTreeUI(this);

            } else {
                switchButtonThemeMode.setDarkMode(true);
                switchButtonThemeMode.toggle();
                SwingUtilities.updateComponentTreeUI(this);
            }
        } else {
            switchButtonThemeMode.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanelSideBarButtons = new javax.swing.JPanel();
        jButtonDashboard = new javax.swing.JButton();
        jButtonBilling = new javax.swing.JButton();
        jButtonReports = new javax.swing.JButton();
        jButtonProduct = new javax.swing.JButton();
        jButtonCustomer = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jButtonUserAccount = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanelSwitchButton = new javax.swing.JPanel();
        switchButtonThemeMode = new com.aldrin.billing.swingx.SwitchButton();
        jPanelContainer = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuApp = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Schema Billing");
        setMinimumSize(new java.awt.Dimension(900, 625));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(160, 10));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanelSideBarButtons.setOpaque(false);
        jPanelSideBarButtons.setPreferredSize(new java.awt.Dimension(10, 225));
        jPanelSideBarButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jButtonDashboard.setIcon(new FlatSVGIcon("svg/dashboard.svg",20,20));
        jButtonDashboard.setText("Dashboard");
        jButtonDashboard.setBorder(null);
        jButtonDashboard.setBorderPainted(false);
        jButtonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonDashboard.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonDashboard.setPreferredSize(new java.awt.Dimension(200, 28));
        jButtonDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDashboardMouseEntered(evt);
            }
        });
        jButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDashboardActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonDashboard);

        jButtonBilling.setIcon(new FlatSVGIcon("svg/billing.svg",20,20));
        jButtonBilling.setText("Billing");
        jButtonBilling.setBorder(null);
        jButtonBilling.setBorderPainted(false);
        jButtonBilling.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBilling.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonBilling.setPreferredSize(new java.awt.Dimension(200, 28));
        jButtonBilling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBillingMouseEntered(evt);
            }
        });
        jButtonBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillingActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonBilling);

        jButtonReports.setIcon(new FlatSVGIcon("svg/report.svg",20,20));
        jButtonReports.setText("Reports");
        jButtonReports.setBorder(null);
        jButtonReports.setBorderPainted(false);
        jButtonReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonReports.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonReports.setPreferredSize(new java.awt.Dimension(200, 28));
        jButtonReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonReportsMouseEntered(evt);
            }
        });
        jButtonReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportsActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonReports);

        jButtonProduct.setIcon(new FlatSVGIcon("svg/product.svg",20,20));
        jButtonProduct.setText("Product");
        jButtonProduct.setBorder(null);
        jButtonProduct.setBorderPainted(false);
        jButtonProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonProduct.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonProduct.setPreferredSize(new java.awt.Dimension(200, 28));
        jButtonProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonProductMouseEntered(evt);
            }
        });
        jButtonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonProduct);

        jButtonCustomer.setIcon(new FlatSVGIcon("svg/customer.svg",20,20));
        jButtonCustomer.setText("Customer");
        jButtonCustomer.setBorder(null);
        jButtonCustomer.setBorderPainted(false);
        jButtonCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCustomer.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonCustomer.setPreferredSize(new java.awt.Dimension(200, 28));
        jButtonCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCustomerMouseEntered(evt);
            }
        });
        jButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonCustomer);

        jButtonUser.setIcon(new FlatSVGIcon("svg/user.svg",20,20));
        jButtonUser.setText("User");
        jButtonUser.setBorder(null);
        jButtonUser.setBorderPainted(false);
        jButtonUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonUser.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonUser.setPreferredSize(new java.awt.Dimension(200, 28));
        jButtonUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUserMouseEntered(evt);
            }
        });
        jButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonUser);

        jButtonUserAccount.setIcon(new FlatSVGIcon("svg/login.svg",20,20));
        jButtonUserAccount.setText("User Account");
        jButtonUserAccount.setBorder(null);
        jButtonUserAccount.setBorderPainted(false);
        jButtonUserAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonUserAccount.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonUserAccount.setPreferredSize(new java.awt.Dimension(200, 28));
        jButtonUserAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUserAccountMouseEntered(evt);
            }
        });
        jButtonUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserAccountActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonUserAccount);

        jButtonLogin.setIcon(new FlatSVGIcon("svg/login.svg",20,20));
        jButtonLogin.setText("Login");
        jButtonLogin.setBorder(null);
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLogin.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonLogin.setPreferredSize(new java.awt.Dimension(200, 28));
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseEntered(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonLogin);

        jPanel4.add(jPanelSideBarButtons, java.awt.BorderLayout.NORTH);

        jPanel7.setOpaque(false);
        jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanelSwitchButton.setPreferredSize(new java.awt.Dimension(10, 60));
        jPanelSwitchButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        switchButtonThemeMode.setMinimumSize(new java.awt.Dimension(60, 30));
        switchButtonThemeMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchButtonThemeModeMouseClicked(evt);
            }
        });
        jPanelSwitchButton.add(switchButtonThemeMode);

        jPanel4.add(jPanelSwitchButton, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanelContainer.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanelContainer, java.awt.BorderLayout.CENTER);

        jPanel6.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel6, java.awt.BorderLayout.EAST);
        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuApp.setText("App");

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuApp.add(jMenuItemLogin);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuApp.add(jMenuItemLogout);
        jMenuApp.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuApp.add(jMenuItem2);

        jMenuBar1.add(jMenuApp);

        jMenuSettings.setText("Settings");

        jMenuItem3.setText("User");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItem3);

        jMenuBar1.add(jMenuSettings);

        jMenu2.setText("Help");

        jMenuItem1.setText("About");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Theme");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Graphite");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Graphite Aqua");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Business");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Business Black Steel");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Business Blue Steel");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("AutumnSkin");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("CremeSkin");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("CeruleanSkin");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("GeminiSkin");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("MagellanSkin");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem14.setText("ModerateSkin");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuItem15.setText("NebulaSkin");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuItem16.setText("SaharaSkin");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem16);

        jMenuItem17.setText("TwilightSkin");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1222, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        JDialogLogin login = new JDialogLogin(this, true);
        login.setVisible(true);

        loginUser();


    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed

        logoutSideBar(true);
        jPanelSwitchButton.setVisible(false);
        cardsPanel.setVisible(false);
        clearLoginCredentials();
        loginUser.setUser(null);
        loginUser();
        JDialogLogin login = new JDialogLogin(this, true);
        login.setVisible(true);
        loginUser();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed

        cardLayout.show(cardsPanel, "Dashboard");
        buttonSelected(jButtonDashboard);

    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillingActionPerformed
        cardLayout.show(cardsPanel, "Billing");
        buttonSelected(jButtonBilling);
    }//GEN-LAST:event_jButtonBillingActionPerformed

    private void jButtonProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductActionPerformed
        cardLayout.show(cardsPanel, "Product");
        buttonSelected(jButtonProduct);
    }//GEN-LAST:event_jButtonProductActionPerformed

    private void jButtonReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportsActionPerformed
        cardLayout.show(cardsPanel, "Report");
        buttonSelected(jButtonReports);
    }//GEN-LAST:event_jButtonReportsActionPerformed

    private void jButtonDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDashboardMouseEntered
//        buttonMouseEntered(jButtonDashboard);
    }//GEN-LAST:event_jButtonDashboardMouseEntered

    private void jButtonBillingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBillingMouseEntered
//        buttonMouseEntered(jButtonBilling);
    }//GEN-LAST:event_jButtonBillingMouseEntered

    private void jButtonProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProductMouseEntered
//        buttonMouseEntered(jButtonProduct);
    }//GEN-LAST:event_jButtonProductMouseEntered

    private void jButtonReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReportsMouseEntered
//        buttonMouseEntered(jButtonReports);
    }//GEN-LAST:event_jButtonReportsMouseEntered

    private void jButtonUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserMouseEntered

    private void jButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserActionPerformed
        cardLayout.show(cardsPanel, "User");
        buttonSelected(jButtonUser);

    }//GEN-LAST:event_jButtonUserActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
//        switchLAF(jMenuItem1.getText());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
//        switchLAF(jMenuItem2.getText());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
//        switchLAF(jMenuItem3.getText());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
//        switchLAF(jMenuItem4.getText());
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
//        switchLAF(jMenuItem5.getText());
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
//        switchLAF(jMenuItem9.getText());
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
//        switchLAF(jMenuItem10.getText());
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
//        switchLAF(jMenuItem11.getText());
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
//        switchLAF(jMenuItem12.getText());
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
//        switchLAF(jMenuItem13.getText());
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
//        switchLAF(jMenuItem14.getText());
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
//        switchLAF(jMenuItem15.getText());
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
//        switchLAF(jMenuItem16.getText());
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
//        switchLAF(jMenuItem17.getText());
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jButtonCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCustomerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCustomerMouseEntered

    private void jButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerActionPerformed
        cardLayout.show(cardsPanel, "Customer");
        buttonSelected(jButtonCustomer);
    }//GEN-LAST:event_jButtonCustomerActionPerformed

    private void switchButtonThemeModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchButtonThemeModeMouseClicked
        if (switchButtonThemeMode.isDarkMode() == true) {
            String selectedLafClass = lafClasses[1];
            LookAndFeelManager.applyLookAndFeel(selectedLafClass, this);
            LookAndFeelManager.saveLookAndFeel(selectedLafClass);
            SwingUtilities.updateComponentTreeUI(this);
        } else {
            String selectedLafClass = lafClasses[0];
            LookAndFeelManager.applyLookAndFeel(selectedLafClass, this);
            LookAndFeelManager.saveLookAndFeel(selectedLafClass);
            SwingUtilities.updateComponentTreeUI(this);
        }


    }//GEN-LAST:event_switchButtonThemeModeMouseClicked

    private void jButtonUserAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUserAccountMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserAccountMouseEntered

    private void jButtonUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserAccountActionPerformed
        buttonSelected(jButtonUserAccount);
    }//GEN-LAST:event_jButtonUserAccountActionPerformed

    private void jButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoginMouseEntered

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        JDialogLogin login = new JDialogLogin(this, true);
        login.setVisible(true);

        loginUser();
    }//GEN-LAST:event_jButtonLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBilling;
    private javax.swing.JButton jButtonCustomer;
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonProduct;
    private javax.swing.JButton jButtonReports;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JButton jButtonUserAccount;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuApp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelSideBarButtons;
    private javax.swing.JPanel jPanelSwitchButton;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static com.aldrin.billing.swingx.SwitchButton switchButtonThemeMode;
    // End of variables declaration//GEN-END:variables
private void loginUser() {
        SwingUtilities.invokeLater(() -> {
            if (loginUser.getUser() != null) {
//            login 
                logoutSideBar(false);
                JPanelDashboard dashBoard = new JPanelDashboard(this);
                dashBoard.updateUI();
                dashBoard.addPanels();
                dashBoard.updateUI();
                cardsPanel.setVisible(true);
                cardsPanel.add(dashBoard, "Dashboard");

                cardsPanel.add(new JPanelBilling(this), "Billing");
                cardsPanel.add(new JPanelProduct(this), "Product");
                cardsPanel.add(new JPanelReport(this), "Report");
                cardsPanel.add(new JPanelUser(this), "User");
                cardsPanel.add(new JPanelCustomer(this), "Customer");

//                cardLayout.show(cardsPanel, "Dashboard");
//                buttonSelected(jButtonDashboard);
                jPanelContainer.add(cardsPanel, BorderLayout.CENTER);
                jMenuApp.setText(loginUser.getUser().getSurname() + ", " + loginUser.getUser().getFirstname());
                jMenuItemLogout.setVisible(true);
                jMenuItemLogin.setVisible(false);
//                jPanelSideBarButtons.setVisible(true);
                jPanelSwitchButton.setVisible(true);
                displayPicture(loginUser.getUser());
                cardLayout.show(cardsPanel, "Dashboard");
                buttonSelected(jButtonDashboard);
                jPanelContainer.setVisible(true);
            } else {
//            logout
                logoutSideBar(true);
                jMenuApp.setText("App");
                jMenuItemLogout.setVisible(false);
                jMenuSettings.setVisible(false);
                jMenuItemLogin.setVisible(true);
//                jPanelSideBarButtons.setVisible(false);
                jPanelSwitchButton.setVisible(false);
                jPanelContainer.setVisible(false);

            }
        });

    }

    private void clearLoginCredentials() {
        try {
            preferences.remove(USERNAME_PREF_KEY);
            preferences.remove(PASSWORD_PREF_KEY);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
//

    private void saveLoginCredentials() {
        try {
            UserDAOImpl userDAOImpl = new UserDAOImpl();
            User user = new User();
            String storedUsername = preferences.get(USERNAME_PREF_KEY, null);
            String storedPassword = preferences.get(PASSWORD_PREF_KEY, null);
            user.setUsername(storedUsername);
            if (storedPassword == null) {
                loginUser();
                JDialogLogin logIn = new JDialogLogin(this, true);
                logIn.setVisible(true);
                loginUser();
                switchButtonThemeMode.setVisible(false);
            } else {
                user.setPassword(storedPassword);
                if (userDAOImpl.loginUser(user) != null) {
                    switchButtonThemeMode.setVisible(true);
                    LoginUser logInUser = new LoginUser();
                    user = userDAOImpl.loginUser(user);
                    logInUser.setUser(user);
                    loginUser();
                    displayPicture(logInUser.getUser());
//                    jPanelContainer.setVisible(true);
                    // login for jdialog
                } else {
                    loginUser();
                    JDialogLogin logIn = new JDialogLogin(this, true);
                    logIn.setVisible(true);
                    loginUser();
                    switchButtonThemeMode.setVisible(false);
                }
            }

            addPanels();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void displayPicture(User user) {

        try {
            byte[] imageData = user.getPhoto();
            ImageIcon imageIcon = new ImageIcon(imageData);

            ProfileIcon icon = new ProfileIcon();
            icon.setIcon(new ImageIcon(imageIcon.getImage()));
            icon.setBorderSize(1);
            jButtonUserAccount.setMargin(new Insets(1, 10, 1, 1));
            jButtonUserAccount.setIcon(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private Image getCircleImage(Image img, int width, int height) {
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = image.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        Ellipse2D.Double circle = new Ellipse2D.Double(0, 0, width, height);
        g2.setClip(circle);
        g2.drawImage(img, 0, 0, width, height, null);
        g2.dispose();
        return image;
    }

    private void addPanels() {
        cardsPanel = new JPanel(cardLayout);
        cardsPanel.add(new JPanelDashboard(this), "Dashboard");
        cardsPanel.add(new JPanelBilling(this), "Billing");
        cardsPanel.add(new JPanelProduct(this), "Product");
        cardsPanel.add(new JPanelReport(this), "Report");
        cardsPanel.add(new JPanelUser(this), "User");
        cardsPanel.add(new JPanelCustomer(this), "Customer");
    }

    java.awt.Color backgroundColor = new java.awt.Color(102, 102, 102);

    private void buttonSelected(JButton button) {

        if (jButtonDashboard == button) {
            jButtonDashboard.setBackground(backgroundColor);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonUserAccount.setBackground(null);
        } else if (jButtonBilling == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(backgroundColor);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonUserAccount.setBackground(null);
        } else if (jButtonProduct == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(backgroundColor);
            jButtonReports.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonUserAccount.setBackground(null);
        } else if (jButtonReports == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(backgroundColor);
            jButtonCustomer.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonUserAccount.setBackground(null);
        } else if (jButtonUser == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUser.setBackground(backgroundColor);
            jButtonUserAccount.setBackground(null);
        } else if (jButtonCustomer == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonCustomer.setBackground(backgroundColor);
            jButtonUserAccount.setBackground(null);
        }  else if (jButtonUserAccount == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonUserAccount.setBackground(backgroundColor);

        }
    }

    private void buttonMouseEntered(JButton button) {

        if (jButtonDashboard == button) {
            jButtonDashboard.setBackground(backgroundColor);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUserAccount.setBackground(null);
        } else if (jButtonBilling == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(backgroundColor);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUserAccount.setBackground(null);
        } else if (jButtonProduct == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(backgroundColor);
            jButtonReports.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUserAccount.setBackground(null);
        } else if (jButtonReports == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(backgroundColor);
            jButtonUser.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUserAccount.setBackground(null);
        } else if (jButtonCustomer == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonCustomer.setBackground(backgroundColor);
            jButtonUserAccount.setBackground(null);
        }  else if (jButtonUserAccount == button) {
            jButtonDashboard.setBackground(null);
            jButtonBilling.setBackground(null);
            jButtonProduct.setBackground(null);
            jButtonReports.setBackground(null);
            jButtonUser.setBackground(null);
            jButtonCustomer.setBackground(null);
            jButtonUserAccount.setBackground(backgroundColor);
        }
    }

    String[] lafNames = {
        "FlatLightLaf", "FlatDarkLaf"

    };

    String[] lafClasses = {
        "FlatLightLaf", "FlatDarkLaf"
    };

    String lafClassName = LookAndFeelManager.loadLookAndFeel();

    private void popUpUser(JFrameApp jFrameApp) {
        // Create the JPopupMenu
        JPopupMenu popupMenu = new JPopupMenu();
        Separator jSeparatorUser = new Separator();

        // Add regular menu items to the popup menu
        JMenuItem itemChangePassword = new JMenuItem("Change Password");
        JMenuItem itemLogout = new JMenuItem("Logout");
        JMenuItem itemLogin = new JMenuItem("Login");
        JMenuItem itemExit = new JMenuItem("Exit");
        itemChangePassword.setIcon(new FlatSVGIcon("svg/change_password.svg",20,20));
        itemLogout.setIcon(new FlatSVGIcon("svg/logout.svg",20,20));
        itemLogin.setIcon(new FlatSVGIcon("svg/login.svg",20,20));
        itemExit.setIcon(new FlatSVGIcon("svg/close.svg",20,20));
        if (new LoginUser().getUser() == null) {
            popupMenu.add(itemLogin);
            popupMenu.add(jSeparatorUser);
            popupMenu.add(itemExit);
        } else {
            popupMenu.add(itemChangePassword);
            popupMenu.add(itemLogout);
            popupMenu.add(jSeparatorUser);
            popupMenu.add(itemExit);
        }

        // Add action listeners for the main menu items
        itemChangePassword.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JDialogChangePassword changePassword = new JDialogChangePassword(jFrameApp,true);
                changePassword.setVisible(true);
            }
        });

        itemLogout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                logoutSideBar(true);
                jPanelSwitchButton.setVisible(false);
                cardsPanel.setVisible(false);
                clearLoginCredentials();
                loginUser.setUser(null);
                loginUser();
                JDialogLogin login = new JDialogLogin(jFrameApp, true);
                login.setVisible(true);
                loginUser();
            }
        });

        // Add an ActionListener for the JButton
        jButtonUserAccount.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Show the popup menu when the button is clicked
                popupMenu.show(jButtonUserAccount, jButtonUserAccount.getWidth() / 2, jButtonUserAccount.getHeight() / 2);
            }
        });
    }

    private void logoutSideBar(boolean logout) {
        try {
            if (logout == true) {
                jPanelSideBarButtons.removeAll();
                jPanelSideBarButtons.add(jButtonLogin);
                
            } else {
                jPanelSideBarButtons.removeAll();
                jButtonUserAccount.setText(new LoginUser().getUser().getSurname()+", "+new LoginUser().getUser().getFirstname());
                jPanelSideBarButtons.add(jButtonDashboard);
                jPanelSideBarButtons.add(jButtonBilling);
                jPanelSideBarButtons.add(jButtonReports);
                jPanelSideBarButtons.add(jButtonProduct);
                jPanelSideBarButtons.add(jButtonCustomer);
                jPanelSideBarButtons.add(jButtonUser);
                if (loginUser.getUser().getRole().getRole().equals("ADMIN")) {
                  //for settings
                }
                jPanelSideBarButtons.add(jButtonUserAccount);
            }
            jPanel4.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
